import { chmod, mkdir } from "node:fs/promises";
import path from "node:path";
import { expandHome } from "../core/resolution.js";
import type { IdealityConfig } from "../domain/config.js";

export interface RenderedGitConfig {
  includes: string;
  identities: Record<string, string>;
}

function gitValue(value: string): string {
  if (/[\r\n]/.test(value)) {
    throw new Error("Git identity values cannot contain newlines");
  }
  return `"${value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\t", "\\t")}"`;
}

function shellValue(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function renderGitIncludes(
  config: IdealityConfig,
  home: string,
  idealityHome: string,
): RenderedGitConfig {
  const lines = ["# Generated by ideality. Do not edit.", ""];
  const identities: Record<string, string> = {};

  for (const [id, identity] of Object.entries(config.identities).sort(
    ([a], [b]) => a.localeCompare(b),
  )) {
    if (!identity.git) {
      continue;
    }
    const identityPath = path.join(idealityHome, "git", `${id}.gitconfig`);
    identities[id] = [
      "# Generated by ideality. Do not edit.",
      "[user]",
      `\tname = ${gitValue(identity.git.name)}`,
      `\temail = ${gitValue(identity.git.email)}`,
      ...(identity.git.signingKey
        ? [`\tsigningKey = ${gitValue(identity.git.signingKey)}`]
        : []),
      ...(identity.git.gpgSign === undefined
        ? []
        : [
            "[commit]",
            `\tgpgSign = ${identity.git.gpgSign ? "true" : "false"}`,
          ]),
      ...(identity.git.sshKey
        ? [
            "[core]",
            `\tsshCommand = ${gitValue(
              `ssh -i ${shellValue(expandHome(identity.git.sshKey, home))} -o IdentitiesOnly=yes`,
            )}`,
          ]
        : []),
      "",
    ].join("\n");

    for (const configuredRoot of identity.roots) {
      const root = `${expandHome(configuredRoot, home).replace(/\/+$/, "")}/`;
      lines.push(
        `[includeIf "gitdir:${root}"]`,
        `\tpath = ${gitValue(identityPath)}`,
        "",
      );
    }
  }

  return { includes: lines.join("\n"), identities };
}

export async function installGitIntegration(
  config: IdealityConfig,
  home: string,
  idealityHome: string,
): Promise<string> {
  const rendered = renderGitIncludes(config, home, idealityHome);
  const directory = path.join(idealityHome, "git");
  const includesPath = path.join(directory, "includes.gitconfig");
  await mkdir(directory, { recursive: true, mode: 0o700 });
  await Bun.write(includesPath, rendered.includes);
  await chmod(includesPath, 0o600);

  for (const [id, content] of Object.entries(rendered.identities)) {
    const identityPath = path.join(directory, `${id}.gitconfig`);
    await Bun.write(identityPath, content);
    await chmod(identityPath, 0o600);
  }

  const inspect = Bun.spawnSync({
    cmd: ["git", "config", "--global", "--get-all", "include.path"],
    stdout: "pipe",
    stderr: "pipe",
  });
  const registered = inspect.stdout
    .toString()
    .split("\n")
    .some((entry) => path.resolve(entry.trim()) === includesPath);

  if (!registered) {
    const add = Bun.spawnSync({
      cmd: ["git", "config", "--global", "--add", "include.path", includesPath],
      stdout: "pipe",
      stderr: "pipe",
    });
    if (add.exitCode !== 0) {
      throw new Error(
        `Failed to register Git config: ${add.stderr.toString().trim()}`,
      );
    }
  }

  return includesPath;
}
