// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Audit from '../src/commands/audit.js'
import Auth from '../src/commands/auth.js'
import Completion from '../src/commands/completion.js'
import Config from '../src/commands/config.js'
import Doctor from '../src/commands/doctor.js'
import Env from '../src/commands/env.js'
import Explain from '../src/commands/explain.js'
import Hook from '../src/commands/hook.js'
import Identity from '../src/commands/identity.js'
import Init from '../src/commands/init.js'
import Install from '../src/commands/install.js'
import Network from '../src/commands/network.js'
import Plugin from '../src/commands/plugin.js'
import Policy from '../src/commands/policy.js'
import Prompt from '../src/commands/prompt.js'
import Rollback from '../src/commands/rollback.js'
import Run from '../src/commands/run.js'
import Secret from '../src/commands/secret.js'
import Setup from '../src/commands/setup.js'
import Status from '../src/commands/status.js'
import Tool from '../src/commands/tool.js'
import Tui from '../src/commands/tui.js'
import Update from '../src/commands/update.js'
import Vm from '../src/commands/vm.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['audit', 'auth', 'completion', 'config', 'doctor', 'env', 'explain', 'hook', 'identity', 'init', 'install', 'network', 'plugin', 'policy', 'prompt', 'rollback', 'run', 'secret', 'setup', 'status', 'tool', 'tui', 'update', 'vm'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'audit': Audit,
  'auth': Auth,
  'completion': Completion,
  'config': Config,
  'doctor': Doctor,
  'env': Env,
  'explain': Explain,
  'hook': Hook,
  'identity': Identity,
  'init': Init,
  'install': Install,
  'network': Network,
  'plugin': Plugin,
  'policy': Policy,
  'prompt': Prompt,
  'rollback': Rollback,
  'run': Run,
  'secret': Secret,
  'setup': Setup,
  'status': Status,
  'tool': Tool,
  'tui': Tui,
  'update': Update,
  'vm': Vm
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'audit': {
      name: 'audit',
      description: 'Administer opt-in local structured audit history',
      commands: [
        {
          name: 'status',
          description: 'Inspect audit history settings and local storage',
          options: {
            'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2450,"end":2455,"loc":{"start":{"line":90,"column":41,"index":2450},"end":{"line":90,"column":46,"index":2455}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/audit'
        },
        {
          name: 'enable',
          description: 'Enable local audit history recording',
          options: {
            'max-events': { type: 'z.coerce.number.int.min.optional', required: false, hasDefault: false, description: 'Maximum retained events', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'max-bytes': { type: 'z.coerce.number.int.min.optional', required: false, hasDefault: false, description: 'Maximum audit file size in bytes', min: 1024, minLength: 1024, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'retention-days': { type: 'z.coerce.number.int.min.optional', required: false, hasDefault: false, description: 'Maximum retained event age in days', min: 1, minLength: 1, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/audit'
        },
        {
          name: 'disable',
          description: 'Disable local audit history recording',
          path: './src/commands/audit'
        },
        {
          name: 'list',
          description: 'List audit events',
          options: {
            'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5742,"end":5747,"loc":{"start":{"line":181,"column":41,"index":5742},"end":{"line":181,"column":46,"index":5747}},"value":false}}]}, validator: '(val) => true' },
            'type': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Filter by event type', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'since': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Only show events at or after this ISO timestamp', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'until': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Only show events at or before this ISO timestamp', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'limit': { type: 'z.coerce.number.int.min.optional', required: false, hasDefault: false, description: 'Show the newest N matching events', min: 0, minLength: 0, schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/audit'
        },
        {
          name: 'prune',
          description: 'Apply configured audit retention now',
          options: {
            'confirm': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm audit history pruning', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7511,"end":7516,"loc":{"start":{"line":232,"column":44,"index":7511},"end":{"line":232,"column":49,"index":7516}},"value":false}}]}, validator: '(val) => true' },
            'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON errors', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7662,"end":7667,"loc":{"start":{"line":236,"column":41,"index":7662},"end":{"line":236,"column":46,"index":7667}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/audit'
        },
        {
          name: 'clear',
          description: 'Clear local audit history',
          options: {
            'confirm': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm audit history deletion', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8579,"end":8584,"loc":{"start":{"line":265,"column":44,"index":8579},"end":{"line":265,"column":49,"index":8584}},"value":false}}]}, validator: '(val) => true' },
            'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON errors', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8731,"end":8736,"loc":{"start":{"line":269,"column":41,"index":8731},"end":{"line":269,"column":46,"index":8736}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/audit'
        }
      ],
      path: './src/commands/audit'
    },
  'auth': {
      name: 'auth',
      description: 'Manage a tool\'s authentication inside one identity',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'all': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Report auth status for every identity/tool pairing', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1126,"end":1131,"loc":{"start":{"line":35,"column":36,"index":1126},"end":{"line":35,"column":41,"index":1131}},"value":false}}]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON (with --all)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1282,"end":1287,"loc":{"start":{"line":39,"column":37,"index":1282},"end":{"line":39,"column":42,"index":1287}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/auth'
    },
  'completion': {
      name: 'completion',
      description: 'Generate shell completions',
      options: {
        'install': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Install the generated completion under ~/.ideality', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":476,"end":481,"loc":{"start":{"line":16,"column":40,"index":476},"end":{"line":16,"column":45,"index":481}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/completion'
    },
  'config': {
      name: 'config',
      description: 'Inspect or edit the registry',
      commands: [
        {
          name: 'path',
          description: 'Print the registry path',
          path: './src/commands/config'
        },
        {
          name: 'validate',
          description: 'Validate the registry',
          path: './src/commands/config'
        },
        {
          name: 'show',
          description: 'Print the registry (secrets are references only)',
          path: './src/commands/config'
        },
        {
          name: 'migrate',
          description: 'Migrate the registry to the current schema version',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the migration plan without writing', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1478,"end":1483,"loc":{"start":{"line":50,"column":46,"index":1478},"end":{"line":50,"column":51,"index":1483}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/config'
        },
        {
          name: 'edit',
          description: 'Open the registry in $EDITOR',
          path: './src/commands/config'
        }
      ],
      path: './src/commands/config'
    },
  'doctor': {
      name: 'doctor',
      description: 'Audit identity configuration and local tooling',
      options: {
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":437,"end":442,"loc":{"start":{"line":14,"column":37,"index":437},"end":{"line":14,"column":42,"index":442}},"value":false}}]}, validator: '(val) => true' },
        'strict': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Treat warnings as failures', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":554,"end":559,"loc":{"start":{"line":18,"column":39,"index":554},"end":{"line":18,"column":44,"index":559}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/doctor'
    },
  'env': {
      name: 'env',
      description: 'Render the selected identity environment',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'shell': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Emit shell assignments instead of JSON', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'reveal': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Include resolved values in JSON output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":883,"end":888,"loc":{"start":{"line":27,"column":39,"index":883},"end":{"line":27,"column":44,"index":888}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/env'
    },
  'explain': {
      name: 'explain',
      description: 'Explain how a tool invocation will be isolated',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":694,"end":699,"loc":{"start":{"line":20,"column":37,"index":694},"end":{"line":20,"column":42,"index":699}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/explain'
    },
  'hook': {
      name: 'hook',
      description: 'Print a shell hook',
      path: './src/commands/hook'
    },
  'identity': {
      name: 'identity',
      description: 'Create and manage identities',
      alias: 'id',
      commands: [
        {
          name: 'list',
          description: 'List identities',
          path: './src/commands/identity'
        },
        {
          name: 'show',
          description: 'Show one identity',
          path: './src/commands/identity'
        },
        {
          name: 'ssh-public',
          description: 'Print an identity\'s SSH public key',
          path: './src/commands/identity'
        },
        {
          name: 'add',
          description: 'Create an identity and optional SSH key',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived identity ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'root': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Directory root (defaults to ~/code/<id>)', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'color': { type: 'z.string.default', required: true, hasDefault: true, default: "#22d3ee", description: 'TUI accent color', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"#22d3ee"}]}, validator: '(val) => true' },
            'git-name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Git author name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'git-email': { type: 'z.string.email.optional', required: false, hasDefault: false, description: 'Git author email', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'ssh-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Existing SSH private key', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'generate-ssh': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate a new Ed25519 key', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4911,"end":4916,"loc":{"start":{"line":153,"column":51,"index":4911},"end":{"line":153,"column":56,"index":4916}},"value":false}}]}, validator: '(val) => true' },
            'packs': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated built-in tool packs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools enabled for the identity', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Force the identity wizard', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5319,"end":5324,"loc":{"start":{"line":163,"column":48,"index":5319},"end":{"line":163,"column":53,"index":5324}},"value":false}}]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; derive the ID from the label', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5479,"end":5484,"loc":{"start":{"line":167,"column":54,"index":5479},"end":{"line":167,"column":59,"index":5484}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the identity without changing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5648,"end":5653,"loc":{"start":{"line":171,"column":46,"index":5648},"end":{"line":171,"column":51,"index":5653}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'remove',
          description: 'Remove an identity without deleting its files',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip confirmation', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":16180,"end":16185,"loc":{"start":{"line":476,"column":42,"index":16180},"end":{"line":476,"column":47,"index":16185}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":16346,"end":16351,"loc":{"start":{"line":481,"column":46,"index":16346},"end":{"line":481,"column":51,"index":16351}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'bind',
          description: 'Bind an additional directory root',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":17622,"end":17627,"loc":{"start":{"line":519,"column":46,"index":17622},"end":{"line":519,"column":51,"index":17627}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'unbind',
          description: 'Remove a directory binding',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":18579,"end":18584,"loc":{"start":{"line":545,"column":46,"index":18579},"end":{"line":545,"column":51,"index":18584}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'default',
          description: 'Set the fallback identity',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":19647,"end":19652,"loc":{"start":{"line":572,"column":46,"index":19647},"end":{"line":572,"column":51,"index":19652}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        }
      ],
      path: './src/commands/identity'
    },
  'init': {
      name: 'init',
      description: 'Create the identity registry',
      options: {
        'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatic identity ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'label': { type: 'z.string.default', required: true, hasDefault: true, default: "Default", description: 'Display label', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"Default"}]}, validator: '(val) => true' },
        'root': { type: 'z.string.default', required: true, hasDefault: true, default: "~/code", description: 'Directory root owned by this identity', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"~/code"}]}, validator: '(val) => true' },
        'git-name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Git author name (defaults to global Git config)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'git-email': { type: 'z.string.email.optional', required: false, hasDefault: false, description: 'Git author email (defaults to global Git config)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'ssh-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Existing SSH private key', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'generate-ssh': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate an Ed25519 SSH key', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3102,"end":3107,"loc":{"start":{"line":102,"column":47,"index":3102},"end":{"line":102,"column":52,"index":3107}},"value":false}}]}, validator: '(val) => true' },
        'packs': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated built-in tool packs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools enabled for the identity', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'install': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Install shell and Git integrations', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3467,"end":3472,"loc":{"start":{"line":112,"column":40,"index":3467},"end":{"line":112,"column":45,"index":3472}},"value":false}}]}, validator: '(val) => true' },
        'shell': { type: 'z.enum.default', required: true, hasDefault: true, default: undefined, description: 'Shell integration', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"detectedShell","args":[]}]}, validator: '(val) => true' },
        'no-shell': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip shell integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3739,"end":3744,"loc":{"start":{"line":119,"column":43,"index":3739},"end":{"line":119,"column":48,"index":3744}},"value":false}}]}, validator: '(val) => true' },
        'no-git': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip Git integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3871,"end":3876,"loc":{"start":{"line":123,"column":41,"index":3871},"end":{"line":123,"column":46,"index":3876}},"value":false}}]}, validator: '(val) => true' },
        'interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Force the setup wizard', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4004,"end":4009,"loc":{"start":{"line":127,"column":44,"index":4004},"end":{"line":127,"column":49,"index":4009}},"value":false}}]}, validator: '(val) => true' },
        'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; use flags and defaults', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4145,"end":4150,"loc":{"start":{"line":131,"column":50,"index":4145},"end":{"line":131,"column":55,"index":4150}},"value":false}}]}, validator: '(val) => true' },
        'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Overwrite an existing registry', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4288,"end":4293,"loc":{"start":{"line":135,"column":38,"index":4288},"end":{"line":135,"column":43,"index":4293}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the registry and integrations without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4447,"end":4452,"loc":{"start":{"line":140,"column":42,"index":4447},"end":{"line":140,"column":47,"index":4452}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/init'
    },
  'install': {
      name: 'install',
      description: 'Install shell and Git integrations',
      options: {
        'shell': { type: 'z.enum.default', required: true, hasDefault: true, default: "zsh", description: 'Shell integration to install', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"zsh"}]}, validator: '(val) => true' },
        'rc': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override shell rc file', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-shell': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip shell integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1128,"end":1133,"loc":{"start":{"line":36,"column":43,"index":1128},"end":{"line":36,"column":48,"index":1133}},"value":false}}]}, validator: '(val) => true' },
        'no-git': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip Git includeIf integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1260,"end":1265,"loc":{"start":{"line":40,"column":41,"index":1260},"end":{"line":40,"column":46,"index":1265}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show installation targets without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1401,"end":1406,"loc":{"start":{"line":44,"column":42,"index":1401},"end":{"line":44,"column":47,"index":1406}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/install'
    },
  'network': {
      name: 'network',
      description: 'Manage enforced VPN and network profiles',
      alias: 'vpn',
      commands: [
        {
          name: 'list',
          description: 'List network profiles',
          path: './src/commands/network'
        },
        {
          name: 'show',
          description: 'Show one network profile',
          path: './src/commands/network'
        },
        {
          name: 'add',
          description: 'Create a VPN profile with an interactive wizard or flags',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived profile ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'driver': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'VPN driver', enumValues: ["mullvad","tailscale","warp","wireguard","openvpn","custom"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'config': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Config source: file:path, secret:key, env:NAME, or value:text', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'username': { type: 'z.string.optional', required: false, hasDefault: false, description: 'OpenVPN username source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'password': { type: 'z.string.optional', required: false, hasDefault: false, description: 'OpenVPN password source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'country': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay country', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'city': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay city', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'hostname': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay hostname', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'exit-node': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Tailscale exit-node hostname or IP', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-lan-access': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow LAN access while using a Tailscale exit node', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6085,"end":6090,"loc":{"start":{"line":183,"column":55,"index":6085},"end":{"line":183,"column":60,"index":6090}},"value":false}}]}, validator: '(val) => true' },
            'accept-routes': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Accept Tailscale subnet routes', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6268,"end":6272,"loc":{"start":{"line":187,"column":52,"index":6268},"end":{"line":187,"column":56,"index":6272}},"value":true}}]}, validator: '(val) => true' },
            'shields-up': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Block incoming Tailscale connections', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6395,"end":6400,"loc":{"start":{"line":190,"column":49,"index":6395},"end":{"line":190,"column":54,"index":6400}},"value":false}}]}, validator: '(val) => true' },
            'dns': { type: 'z.string.default', required: true, hasDefault: true, default: "provider", description: 'Mullvad DNS: provider or comma-separated server list', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"provider"}]}, validator: '(val) => true' },
            'ipv6': { type: 'z.enum.default', required: true, hasDefault: true, default: "tunnel", description: 'Mullvad IPv6 policy', enumValues: ["tunnel","block"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"tunnel"}]}, validator: '(val) => true' },
            'lan': { type: 'z.enum.default', required: true, hasDefault: true, default: "deny", description: 'Mullvad local-network policy', enumValues: ["deny","allow"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"deny"}]}, validator: '(val) => true' },
            'kill-switch': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Required enforcement level', enumValues: ["required","provider","off"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'connect': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom connect command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'disconnect': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom disconnect command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'status': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom status command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'verified-kill-switch': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Attest that the custom adapter enforces a kill switch', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7540,"end":7545,"loc":{"start":{"line":216,"column":59,"index":7540},"end":{"line":216,"column":64,"index":7545}},"value":false}}]}, validator: '(val) => true' },
            'sudo': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Run WireGuard/OpenVPN provider commands through sudo', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7715,"end":7720,"loc":{"start":{"line":220,"column":41,"index":7715},"end":{"line":220,"column":46,"index":7720}},"value":false}}]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7902,"end":7907,"loc":{"start":{"line":224,"column":54,"index":7902},"end":{"line":224,"column":59,"index":7907}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the profile without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8041,"end":8046,"loc":{"start":{"line":228,"column":46,"index":8041},"end":{"line":228,"column":51,"index":8046}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'bind',
          description: 'Require a network for an identity or one tool',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'up',
          description: 'Connect the selected network and acquire the host lease',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3062,"end":3067,"loc":{"start":{"line":98,"column":49,"index":3062},"end":{"line":98,"column":54,"index":3067}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3224,"end":3229,"loc":{"start":{"line":102,"column":40,"index":3224},"end":{"line":102,"column":45,"index":3229}},"value":false}}]}, validator: '(val) => true' },
            'replace': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Disconnect the active profile before switching', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":26114,"end":26119,"loc":{"start":{"line":725,"column":44,"index":26114},"end":{"line":725,"column":49,"index":26119}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'down',
          description: 'Disconnect a network; Mullvad lockdown remains unless released',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3062,"end":3067,"loc":{"start":{"line":98,"column":49,"index":3062},"end":{"line":98,"column":54,"index":3067}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3224,"end":3229,"loc":{"start":{"line":102,"column":40,"index":3224},"end":{"line":102,"column":45,"index":3229}},"value":false}}]}, validator: '(val) => true' },
            'release': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Also disable provider lockdown', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":27291,"end":27296,"loc":{"start":{"line":762,"column":44,"index":27291},"end":{"line":762,"column":49,"index":27296}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'status',
          description: 'Check provider and Ideality lease status',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3062,"end":3067,"loc":{"start":{"line":98,"column":49,"index":3062},"end":{"line":98,"column":54,"index":3067}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3224,"end":3229,"loc":{"start":{"line":102,"column":40,"index":3224},"end":{"line":102,"column":45,"index":3229}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'remove',
          description: 'Remove an unused network profile',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":29370,"end":29375,"loc":{"start":{"line":826,"column":42,"index":29370},"end":{"line":826,"column":47,"index":29375}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        }
      ],
      path: './src/commands/network'
    },
  'plugin': {
      name: 'plugin',
      description: 'Install portable declarative tool integrations',
      commands: [
        {
          name: 'list',
          description: 'List installed plugin manifests',
          path: './src/commands/plugin'
        },
        {
          name: 'validate',
          description: 'Validate a plugin manifest without installing it',
          path: './src/commands/plugin'
        },
        {
          name: 'install',
          description: 'Install or update a plugin manifest',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Replace an existing tool definition', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1881,"end":1886,"loc":{"start":{"line":56,"column":42,"index":1881},"end":{"line":56,"column":47,"index":1886}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the plugin without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2065,"end":2070,"loc":{"start":{"line":61,"column":46,"index":2065},"end":{"line":61,"column":51,"index":2070}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/plugin'
        },
        {
          name: 'remove',
          description: 'Remove a plugin and its identity profiles',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3562,"end":3567,"loc":{"start":{"line":99,"column":42,"index":3562},"end":{"line":99,"column":47,"index":3567}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the removal without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3726,"end":3731,"loc":{"start":{"line":104,"column":46,"index":3726},"end":{"line":104,"column":51,"index":3731}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/plugin'
        }
      ],
      path: './src/commands/plugin'
    },
  'policy': {
      name: 'policy',
      description: 'Team policy contracts for project handovers',
      path: './src/commands/policy'
    },
  'prompt': {
      name: 'prompt',
      description: 'Render the active identity for a shell prompt',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'format': { type: 'z.string.default', required: true, hasDefault: true, default: "[{identity}]", description: 'Template using {identity}, {label}, and {root}', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"[{identity}]"}]}, validator: '(val) => true' }
      },
      path: './src/commands/prompt'
    },
  'rollback': {
      name: 'rollback',
      description: 'List or restore transactional registry snapshots',
      options: {
        'list': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'List available snapshots', short: 'l', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":680,"end":685,"loc":{"start":{"line":21,"column":37,"index":680},"end":{"line":21,"column":42,"index":685}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the target without restoring it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":833,"end":838,"loc":{"start":{"line":26,"column":42,"index":833},"end":{"line":26,"column":47,"index":838}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/rollback'
    },
  'run': {
      name: 'run',
      description: 'Run a tool inside its selected identity',
      alias: 'x',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Permit a configured VPN without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1167,"end":1172,"loc":{"start":{"line":35,"column":51,"index":1167},"end":{"line":35,"column":56,"index":1172}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/run'
    },
  'secret': {
      name: 'secret',
      description: 'Manage process-scoped secret references and backends',
      commands: [
        {
          name: 'set',
          description: 'Securely write a configured secret reference',
          options: {
            'stdin': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Read the value from standard input', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1536,"end":1541,"loc":{"start":{"line":53,"column":42,"index":1536},"end":{"line":53,"column":47,"index":1541}},"value":false}}]}, validator: '(val) => true' },
            'path': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Directory used to resolve a {{root}} template', short: 'C', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the target without reading a value', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1849,"end":1854,"loc":{"start":{"line":61,"column":46,"index":1849},"end":{"line":61,"column":51,"index":1854}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/secret'
        },
        {
          name: 'list',
          description: 'List credential references without reading their values',
          path: './src/commands/secret'
        },
        {
          name: 'backend',
          description: 'Show or select a local or password-manager secret backend',
          options: {
            'directory': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the file or age storage directory', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'recipient': { type: 'z.string.optional', required: false, hasDefault: false, description: 'age recipient used for encryption', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'identity-file': { type: 'z.string.optional', required: false, hasDefault: false, description: 'age identity file used for decryption', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'service': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Desktop keychain service name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'prefix': { type: 'z.string.optional', required: false, hasDefault: false, description: 'pass store prefix', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'app-data-directory': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Bitwarden CLI account data directory', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the backend without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8940,"end":8945,"loc":{"start":{"line":255,"column":46,"index":8940},"end":{"line":255,"column":51,"index":8945}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/secret'
        }
      ],
      path: './src/commands/secret'
    },
  'setup': {
      name: 'setup',
      description: 'Configure the current project with an interactive wizard',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Project directory', short: 'C', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Local identity to activate', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools for non-interactive setup', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'project': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Write a complete .ideality/project.jsonc handover bundle', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5129,"end":5134,"loc":{"start":{"line":161,"column":40,"index":5129},"end":{"line":161,"column":45,"index":5134}},"value":false}}]}, validator: '(val) => true' },
        'local-only': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Keep configuration only under the user ideality home', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5299,"end":5304,"loc":{"start":{"line":165,"column":45,"index":5299},"end":{"line":165,"column":50,"index":5304}},"value":false}}]}, validator: '(val) => true' },
        'advanced': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show SSH, handover, and integration controls', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5461,"end":5466,"loc":{"start":{"line":169,"column":41,"index":5461},"end":{"line":169,"column":46,"index":5466}},"value":false}}]}, validator: '(val) => true' },
        'requirements-only': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Share tool requirements without full identity profiles', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5626,"end":5631,"loc":{"start":{"line":173,"column":52,"index":5626},"end":{"line":173,"column":57,"index":5631}},"value":false}}]}, validator: '(val) => true' },
        'vm': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Run selected tools in this VM profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Require this host-enforced network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; require identity and tool flags as needed', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6025,"end":6030,"loc":{"start":{"line":183,"column":50,"index":6025},"end":{"line":183,"column":55,"index":6030}},"value":false}}]}, validator: '(val) => true' },
        'yes': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Apply without the final confirmation', short: 'y', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6185,"end":6190,"loc":{"start":{"line":187,"column":36,"index":6185},"end":{"line":187,"column":41,"index":6190}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the complete change without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6350,"end":6355,"loc":{"start":{"line":192,"column":42,"index":6350},"end":{"line":192,"column":47,"index":6355}},"value":false}}]}, validator: '(val) => true' },
        'allow-policy-violations': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Bypass .ideality/policy.jsonc violations for this setup invocation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6523,"end":6528,"loc":{"start":{"line":196,"column":58,"index":6523},"end":{"line":196,"column":63,"index":6528}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/setup'
    },
  'status': {
      name: 'status',
      description: 'Show the identity active for a directory',
      alias: ["whoami","current"],
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":841,"end":846,"loc":{"start":{"line":23,"column":37,"index":841},"end":{"line":23,"column":42,"index":846}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/status'
    },
  'tool': {
      name: 'tool',
      description: 'Manage built-in and custom tool adapters',
      commands: [
        {
          name: 'list',
          description: 'List tool definitions',
          path: './src/commands/tool'
        },
        {
          name: 'packs',
          description: 'List built-in tool packs',
          path: './src/commands/tool'
        },
        {
          name: 'add',
          description: 'Register a custom executable',
          options: {
            'executable': { type: 'z.string', required: true, hasDefault: false, description: 'Executable name or path', short: 'x', fileType: 'path', schema: {"type":"zod","method":"string","args":[]}, validator: '(val) => true' },
            'isolation': { type: 'z.enum.default', required: true, hasDefault: true, default: "process", description: 'Environment scope', enumValues: ["shell","process"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"process"}]}, validator: '(val) => true' },
            'description': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Human-readable description', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4860,"end":4865,"loc":{"start":{"line":132,"column":46,"index":4860},"end":{"line":132,"column":51,"index":4865}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'remove',
          description: 'Remove a tool definition and its identity profiles',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6179,"end":6184,"loc":{"start":{"line":168,"column":42,"index":6179},"end":{"line":168,"column":47,"index":6184}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6343,"end":6348,"loc":{"start":{"line":173,"column":46,"index":6343},"end":{"line":173,"column":51,"index":6348}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'env',
          description: 'Set a variable: secret:key, file:path, env:NAME, value:text, or unset',
          options: {
            'optional': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow a missing file or source variable', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7761,"end":7766,"loc":{"start":{"line":212,"column":45,"index":7761},"end":{"line":212,"column":50,"index":7766}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7927,"end":7932,"loc":{"start":{"line":216,"column":46,"index":7927},"end":{"line":216,"column":51,"index":7932}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'args',
          description: 'Replace identity-specific tool arguments',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":9668,"end":9673,"loc":{"start":{"line":260,"column":46,"index":9668},"end":{"line":260,"column":51,"index":9673}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        }
      ],
      path: './src/commands/tool'
    },
  'tui': {
      name: 'tui',
      description: 'Open the interactive identity, plugin, and secret dashboard',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for initial identity selection', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/tui'
    },
  'update': {
      name: 'update',
      description: 'Safely update a direct binary install',
      options: {
        'check': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Check release metadata without downloading or installing', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1566,"end":1571,"loc":{"start":{"line":56,"column":38,"index":1566},"end":{"line":56,"column":43,"index":1571}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Verify the release artifact and migration readiness without replacing the executable', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1733,"end":1738,"loc":{"start":{"line":60,"column":42,"index":1733},"end":{"line":60,"column":47,"index":1738}},"value":false}}]}, validator: '(val) => true' },
        'version': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Install a specific release version when metadata is available', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'allow-downgrade': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Permit an explicit downgrade', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2089,"end":2094,"loc":{"start":{"line":69,"column":50,"index":2089},"end":{"line":69,"column":55,"index":2094}},"value":false}}]}, validator: '(val) => true' },
        'base-url': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the release artifact base URL (used for offline rehearsals)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/update'
    },
  'vm': {
      name: 'vm',
      description: 'Manage isolated execution machines',
      commands: [
        {
          name: 'list',
          description: 'List VM profiles and backend availability',
          path: './src/commands/vm'
        },
        {
          name: 'show',
          description: 'Show one VM profile',
          path: './src/commands/vm'
        },
        {
          name: 'add',
          description: 'Create a VM profile with an interactive wizard or flags',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived profile ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'driver': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'VM backend', enumValues: ["lima","apple-vz","cloud-hypervisor","firecracker","custom"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'cpus': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 4, description: 'Virtual CPUs', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":4922,"end":4923,"loc":{"start":{"line":160,"column":60,"index":4922},"end":{"line":160,"column":61,"index":4923}},"extra":{"rawValue":4,"raw":"4"},"value":4}}]}, validator: '(val) => true' },
            'memory': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 4096, description: 'Memory in MiB', min: 256, minLength: 256, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":5043,"end":5047,"loc":{"start":{"line":163,"column":64,"index":5043},"end":{"line":163,"column":68,"index":5047}},"extra":{"rawValue":4096,"raw":"4096"},"value":4096}}]}, validator: '(val) => true' },
            'disk': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 40, description: 'Disk in GiB', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":5164,"end":5166,"loc":{"start":{"line":166,"column":60,"index":5164},"end":{"line":166,"column":62,"index":5166}},"extra":{"rawValue":40,"raw":"40"},"value":40}}]}, validator: '(val) => true' },
            'image': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Guest image URL or backend image reference', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'provision': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Lima system provisioning scripts as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'instance': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Backend instance name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'vm-type': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Lima virtualization driver', enumValues: ["auto","vz","qemu"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'mount-type': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Lima filesystem transport', enumValues: ["auto","virtiofs","9p","reverse-sshfs"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'rosetta': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable Rosetta in an Apple VZ guest', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5967,"end":5972,"loc":{"start":{"line":186,"column":44,"index":5967},"end":{"line":186,"column":49,"index":5972}},"value":false}}]}, validator: '(val) => true' },
            'video': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable backend video output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6125,"end":6130,"loc":{"start":{"line":190,"column":42,"index":6125},"end":{"line":190,"column":47,"index":6130}},"value":false}}]}, validator: '(val) => true' },
            'guest-home': { type: 'z.string.default', required: true, hasDefault: true, default: "/home/ideality", description: 'Guest home used for path templates', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"/home/ideality"}]}, validator: '(val) => true' },
            'mount': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Host workspace mount source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'workspace-target': { type: 'z.string.default', required: true, hasDefault: true, default: "/workspace", description: 'Guest workspace path', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"/workspace"}]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Host-enforced network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'helper': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Backend helper executable', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'start': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom start command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'stop': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom stop command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'status': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom status command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'exec': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom exec command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7415,"end":7420,"loc":{"start":{"line":221,"column":54,"index":7415},"end":{"line":221,"column":59,"index":7420}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the profile without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7554,"end":7559,"loc":{"start":{"line":225,"column":46,"index":7554},"end":{"line":225,"column":51,"index":7559}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'bind',
          description: 'Route an identity or one tool through a VM and optional VPN',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the VM network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'unbind',
          description: 'Return an identity or one tool to host execution',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Keep a host network requirement', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'start',
          description: 'Start a VM after enforcing its network',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'stop',
          description: 'Stop a VM',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'status',
          description: 'Read VM backend status',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'exec',
          description: 'Execute a command in a VM',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'remove',
          description: 'Remove an unused VM profile without deleting backend disks',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":25305,"end":25310,"loc":{"start":{"line":732,"column":42,"index":25305},"end":{"line":732,"column":47,"index":25310}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        }
      ],
      path: './src/commands/vm'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
