// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Auth from '../src/commands/auth.js'
import Completion from '../src/commands/completion.js'
import Config from '../src/commands/config.js'
import Doctor from '../src/commands/doctor.js'
import Env from '../src/commands/env.js'
import Explain from '../src/commands/explain.js'
import Hook from '../src/commands/hook.js'
import Identity from '../src/commands/identity.js'
import Init from '../src/commands/init.js'
import Install from '../src/commands/install.js'
import Network from '../src/commands/network.js'
import Plugin from '../src/commands/plugin.js'
import Policy from '../src/commands/policy.js'
import Prompt from '../src/commands/prompt.js'
import Rollback from '../src/commands/rollback.js'
import Run from '../src/commands/run.js'
import Secret from '../src/commands/secret.js'
import Setup from '../src/commands/setup.js'
import Status from '../src/commands/status.js'
import Tool from '../src/commands/tool.js'
import Tui from '../src/commands/tui.js'
import Vm from '../src/commands/vm.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['auth', 'completion', 'config', 'doctor', 'env', 'explain', 'hook', 'identity', 'init', 'install', 'network', 'plugin', 'policy', 'prompt', 'rollback', 'run', 'secret', 'setup', 'status', 'tool', 'tui', 'vm'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'auth': Auth,
  'completion': Completion,
  'config': Config,
  'doctor': Doctor,
  'env': Env,
  'explain': Explain,
  'hook': Hook,
  'identity': Identity,
  'init': Init,
  'install': Install,
  'network': Network,
  'plugin': Plugin,
  'policy': Policy,
  'prompt': Prompt,
  'rollback': Rollback,
  'run': Run,
  'secret': Secret,
  'setup': Setup,
  'status': Status,
  'tool': Tool,
  'tui': Tui,
  'vm': Vm
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'auth': {
      name: 'auth',
      description: 'Manage a tool\'s authentication inside one identity',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'all': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Report auth status for every identity/tool pairing', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1065,"end":1070,"loc":{"start":{"line":34,"column":36,"index":1065},"end":{"line":34,"column":41,"index":1070}},"value":false}}]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON (with --all)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1221,"end":1226,"loc":{"start":{"line":38,"column":37,"index":1221},"end":{"line":38,"column":42,"index":1226}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/auth'
    },
  'completion': {
      name: 'completion',
      description: 'Generate shell completions',
      options: {
        'install': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Install the generated completion under ~/.ideality', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":476,"end":481,"loc":{"start":{"line":16,"column":40,"index":476},"end":{"line":16,"column":45,"index":481}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/completion'
    },
  'config': {
      name: 'config',
      description: 'Inspect or edit the registry',
      commands: [
        {
          name: 'path',
          description: 'Print the registry path',
          path: './src/commands/config'
        },
        {
          name: 'validate',
          description: 'Validate the registry',
          path: './src/commands/config'
        },
        {
          name: 'show',
          description: 'Print the registry (secrets are references only)',
          path: './src/commands/config'
        },
        {
          name: 'migrate',
          description: 'Migrate the registry to the current schema version',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the migration plan without writing', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1393,"end":1398,"loc":{"start":{"line":45,"column":46,"index":1393},"end":{"line":45,"column":51,"index":1398}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/config'
        },
        {
          name: 'edit',
          description: 'Open the registry in $EDITOR',
          path: './src/commands/config'
        }
      ],
      path: './src/commands/config'
    },
  'doctor': {
      name: 'doctor',
      description: 'Audit identity configuration and local tooling',
      options: {
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":437,"end":442,"loc":{"start":{"line":14,"column":37,"index":437},"end":{"line":14,"column":42,"index":442}},"value":false}}]}, validator: '(val) => true' },
        'strict': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Treat warnings as failures', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":554,"end":559,"loc":{"start":{"line":18,"column":39,"index":554},"end":{"line":18,"column":44,"index":559}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/doctor'
    },
  'env': {
      name: 'env',
      description: 'Render the selected identity environment',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'shell': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Emit shell assignments instead of JSON', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'reveal': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Include resolved values in JSON output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":883,"end":888,"loc":{"start":{"line":27,"column":39,"index":883},"end":{"line":27,"column":44,"index":888}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/env'
    },
  'explain': {
      name: 'explain',
      description: 'Explain how a tool invocation will be isolated',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":694,"end":699,"loc":{"start":{"line":20,"column":37,"index":694},"end":{"line":20,"column":42,"index":699}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/explain'
    },
  'hook': {
      name: 'hook',
      description: 'Print a shell hook',
      path: './src/commands/hook'
    },
  'identity': {
      name: 'identity',
      description: 'Create and manage identities',
      alias: 'id',
      commands: [
        {
          name: 'list',
          description: 'List identities',
          path: './src/commands/identity'
        },
        {
          name: 'show',
          description: 'Show one identity',
          path: './src/commands/identity'
        },
        {
          name: 'ssh-public',
          description: 'Print an identity\'s SSH public key',
          path: './src/commands/identity'
        },
        {
          name: 'add',
          description: 'Create an identity and optional SSH key',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived identity ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'root': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Directory root (defaults to ~/code/<id>)', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'color': { type: 'z.string.default', required: true, hasDefault: true, default: "#22d3ee", description: 'TUI accent color', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"#22d3ee"}]}, validator: '(val) => true' },
            'git-name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Git author name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'git-email': { type: 'z.string.email.optional', required: false, hasDefault: false, description: 'Git author email', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'ssh-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Existing SSH private key', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'generate-ssh': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate a new Ed25519 key', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4644,"end":4649,"loc":{"start":{"line":145,"column":51,"index":4644},"end":{"line":145,"column":56,"index":4649}},"value":false}}]}, validator: '(val) => true' },
            'packs': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated built-in tool packs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools enabled for the identity', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Force the identity wizard', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5052,"end":5057,"loc":{"start":{"line":155,"column":48,"index":5052},"end":{"line":155,"column":53,"index":5057}},"value":false}}]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; derive the ID from the label', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5212,"end":5217,"loc":{"start":{"line":159,"column":54,"index":5212},"end":{"line":159,"column":59,"index":5217}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the identity without changing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5381,"end":5386,"loc":{"start":{"line":163,"column":46,"index":5381},"end":{"line":163,"column":51,"index":5386}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'remove',
          description: 'Remove an identity without deleting its files',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip confirmation', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":15874,"end":15879,"loc":{"start":{"line":468,"column":42,"index":15874},"end":{"line":468,"column":47,"index":15879}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":16040,"end":16045,"loc":{"start":{"line":473,"column":46,"index":16040},"end":{"line":473,"column":51,"index":16045}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'bind',
          description: 'Bind an additional directory root',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":17252,"end":17257,"loc":{"start":{"line":509,"column":46,"index":17252},"end":{"line":509,"column":51,"index":17257}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'unbind',
          description: 'Remove a directory binding',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":18147,"end":18152,"loc":{"start":{"line":533,"column":46,"index":18147},"end":{"line":533,"column":51,"index":18152}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        },
        {
          name: 'default',
          description: 'Set the fallback identity',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":19151,"end":19156,"loc":{"start":{"line":558,"column":46,"index":19151},"end":{"line":558,"column":51,"index":19156}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/identity'
        }
      ],
      path: './src/commands/identity'
    },
  'init': {
      name: 'init',
      description: 'Create the identity registry',
      options: {
        'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatic identity ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'label': { type: 'z.string.default', required: true, hasDefault: true, default: "Default", description: 'Display label', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"Default"}]}, validator: '(val) => true' },
        'root': { type: 'z.string.default', required: true, hasDefault: true, default: "~/code", description: 'Directory root owned by this identity', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"~/code"}]}, validator: '(val) => true' },
        'git-name': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Git author name (defaults to global Git config)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'git-email': { type: 'z.string.email.optional', required: false, hasDefault: false, description: 'Git author email (defaults to global Git config)', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'ssh-key': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Existing SSH private key', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'generate-ssh': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Generate an Ed25519 SSH key', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3102,"end":3107,"loc":{"start":{"line":102,"column":47,"index":3102},"end":{"line":102,"column":52,"index":3107}},"value":false}}]}, validator: '(val) => true' },
        'packs': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated built-in tool packs', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools enabled for the identity', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'install': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Install shell and Git integrations', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3467,"end":3472,"loc":{"start":{"line":112,"column":40,"index":3467},"end":{"line":112,"column":45,"index":3472}},"value":false}}]}, validator: '(val) => true' },
        'shell': { type: 'z.enum.default', required: true, hasDefault: true, default: undefined, description: 'Shell integration', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"detectedShell","args":[]}]}, validator: '(val) => true' },
        'no-shell': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip shell integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3739,"end":3744,"loc":{"start":{"line":119,"column":43,"index":3739},"end":{"line":119,"column":48,"index":3744}},"value":false}}]}, validator: '(val) => true' },
        'no-git': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip Git integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3871,"end":3876,"loc":{"start":{"line":123,"column":41,"index":3871},"end":{"line":123,"column":46,"index":3876}},"value":false}}]}, validator: '(val) => true' },
        'interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Force the setup wizard', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4004,"end":4009,"loc":{"start":{"line":127,"column":44,"index":4004},"end":{"line":127,"column":49,"index":4009}},"value":false}}]}, validator: '(val) => true' },
        'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; use flags and defaults', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4145,"end":4150,"loc":{"start":{"line":131,"column":50,"index":4145},"end":{"line":131,"column":55,"index":4150}},"value":false}}]}, validator: '(val) => true' },
        'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Overwrite an existing registry', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4288,"end":4293,"loc":{"start":{"line":135,"column":38,"index":4288},"end":{"line":135,"column":43,"index":4293}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the registry and integrations without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4447,"end":4452,"loc":{"start":{"line":140,"column":42,"index":4447},"end":{"line":140,"column":47,"index":4452}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/init'
    },
  'install': {
      name: 'install',
      description: 'Install shell and Git integrations',
      options: {
        'shell': { type: 'z.enum.default', required: true, hasDefault: true, default: "zsh", description: 'Shell integration to install', enumValues: ["zsh","bash","fish"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"zsh"}]}, validator: '(val) => true' },
        'rc': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override shell rc file', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-shell': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip shell integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1128,"end":1133,"loc":{"start":{"line":36,"column":43,"index":1128},"end":{"line":36,"column":48,"index":1133}},"value":false}}]}, validator: '(val) => true' },
        'no-git': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Skip Git includeIf integration', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1260,"end":1265,"loc":{"start":{"line":40,"column":41,"index":1260},"end":{"line":40,"column":46,"index":1265}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show installation targets without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1401,"end":1406,"loc":{"start":{"line":44,"column":42,"index":1401},"end":{"line":44,"column":47,"index":1406}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/install'
    },
  'network': {
      name: 'network',
      description: 'Manage enforced VPN and network profiles',
      alias: 'vpn',
      commands: [
        {
          name: 'list',
          description: 'List network profiles',
          path: './src/commands/network'
        },
        {
          name: 'show',
          description: 'Show one network profile',
          path: './src/commands/network'
        },
        {
          name: 'add',
          description: 'Create a VPN profile with an interactive wizard or flags',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived profile ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'driver': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'VPN driver', enumValues: ["mullvad","tailscale","warp","wireguard","openvpn","custom"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'config': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Config source: file:path, secret:key, env:NAME, or value:text', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'username': { type: 'z.string.optional', required: false, hasDefault: false, description: 'OpenVPN username source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'password': { type: 'z.string.optional', required: false, hasDefault: false, description: 'OpenVPN password source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'country': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay country', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'city': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay city', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'hostname': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Mullvad relay hostname', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'exit-node': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Tailscale exit-node hostname or IP', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-lan-access': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow LAN access while using a Tailscale exit node', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5972,"end":5977,"loc":{"start":{"line":181,"column":55,"index":5972},"end":{"line":181,"column":60,"index":5977}},"value":false}}]}, validator: '(val) => true' },
            'accept-routes': { type: 'z.boolean.default', required: true, hasDefault: true, default: true, description: 'Accept Tailscale subnet routes', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6155,"end":6159,"loc":{"start":{"line":185,"column":52,"index":6155},"end":{"line":185,"column":56,"index":6159}},"value":true}}]}, validator: '(val) => true' },
            'shields-up': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Block incoming Tailscale connections', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6282,"end":6287,"loc":{"start":{"line":188,"column":49,"index":6282},"end":{"line":188,"column":54,"index":6287}},"value":false}}]}, validator: '(val) => true' },
            'dns': { type: 'z.string.default', required: true, hasDefault: true, default: "provider", description: 'Mullvad DNS: provider or comma-separated server list', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"provider"}]}, validator: '(val) => true' },
            'ipv6': { type: 'z.enum.default', required: true, hasDefault: true, default: "tunnel", description: 'Mullvad IPv6 policy', enumValues: ["tunnel","block"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"tunnel"}]}, validator: '(val) => true' },
            'lan': { type: 'z.enum.default', required: true, hasDefault: true, default: "deny", description: 'Mullvad local-network policy', enumValues: ["deny","allow"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"deny"}]}, validator: '(val) => true' },
            'kill-switch': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Required enforcement level', enumValues: ["required","provider","off"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'connect': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom connect command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'disconnect': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom disconnect command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'status': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom status command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'verified-kill-switch': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Attest that the custom adapter enforces a kill switch', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7427,"end":7432,"loc":{"start":{"line":214,"column":59,"index":7427},"end":{"line":214,"column":64,"index":7432}},"value":false}}]}, validator: '(val) => true' },
            'sudo': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Run WireGuard/OpenVPN provider commands through sudo', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7602,"end":7607,"loc":{"start":{"line":218,"column":41,"index":7602},"end":{"line":218,"column":46,"index":7607}},"value":false}}]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7789,"end":7794,"loc":{"start":{"line":222,"column":54,"index":7789},"end":{"line":222,"column":59,"index":7794}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the profile without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7928,"end":7933,"loc":{"start":{"line":226,"column":46,"index":7928},"end":{"line":226,"column":51,"index":7933}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'bind',
          description: 'Require a network for an identity or one tool',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'up',
          description: 'Connect the selected network and acquire the host lease',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2956,"end":2961,"loc":{"start":{"line":96,"column":49,"index":2956},"end":{"line":96,"column":54,"index":2961}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3118,"end":3123,"loc":{"start":{"line":100,"column":40,"index":3118},"end":{"line":100,"column":45,"index":3123}},"value":false}}]}, validator: '(val) => true' },
            'replace': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Disconnect the active profile before switching', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":25483,"end":25488,"loc":{"start":{"line":706,"column":44,"index":25483},"end":{"line":706,"column":49,"index":25488}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'down',
          description: 'Disconnect a network; Mullvad lockdown remains unless released',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2956,"end":2961,"loc":{"start":{"line":96,"column":49,"index":2956},"end":{"line":96,"column":54,"index":2961}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3118,"end":3123,"loc":{"start":{"line":100,"column":40,"index":3118},"end":{"line":100,"column":45,"index":3123}},"value":false}}]}, validator: '(val) => true' },
            'release': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Also disable provider lockdown', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":26310,"end":26315,"loc":{"start":{"line":734,"column":44,"index":26310},"end":{"line":734,"column":49,"index":26315}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'status',
          description: 'Check provider and Ideality lease status',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Explicitly permit a tunnel without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2956,"end":2961,"loc":{"start":{"line":96,"column":49,"index":2956},"end":{"line":96,"column":54,"index":2961}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Print commands without executing them', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3118,"end":3123,"loc":{"start":{"line":100,"column":40,"index":3118},"end":{"line":100,"column":45,"index":3123}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        },
        {
          name: 'remove',
          description: 'Remove an unused network profile',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":27684,"end":27689,"loc":{"start":{"line":780,"column":42,"index":27684},"end":{"line":780,"column":47,"index":27689}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/network'
        }
      ],
      path: './src/commands/network'
    },
  'plugin': {
      name: 'plugin',
      description: 'Install portable declarative tool integrations',
      commands: [
        {
          name: 'list',
          description: 'List installed plugin manifests',
          path: './src/commands/plugin'
        },
        {
          name: 'validate',
          description: 'Validate a plugin manifest without installing it',
          path: './src/commands/plugin'
        },
        {
          name: 'install',
          description: 'Install or update a plugin manifest',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Replace an existing tool definition', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1820,"end":1825,"loc":{"start":{"line":55,"column":42,"index":1820},"end":{"line":55,"column":47,"index":1825}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the plugin without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2004,"end":2009,"loc":{"start":{"line":60,"column":46,"index":2004},"end":{"line":60,"column":51,"index":2009}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/plugin'
        },
        {
          name: 'remove',
          description: 'Remove a plugin and its identity profiles',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3309,"end":3314,"loc":{"start":{"line":94,"column":42,"index":3309},"end":{"line":94,"column":47,"index":3314}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the removal without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":3473,"end":3478,"loc":{"start":{"line":99,"column":46,"index":3473},"end":{"line":99,"column":51,"index":3478}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/plugin'
        }
      ],
      path: './src/commands/plugin'
    },
  'policy': {
      name: 'policy',
      description: 'Team policy contracts for project handovers',
      path: './src/commands/policy'
    },
  'prompt': {
      name: 'prompt',
      description: 'Render the active identity for a shell prompt',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'format': { type: 'z.string.default', required: true, hasDefault: true, default: "[{identity}]", description: 'Template using {identity}, {label}, and {root}', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"[{identity}]"}]}, validator: '(val) => true' }
      },
      path: './src/commands/prompt'
    },
  'rollback': {
      name: 'rollback',
      description: 'List or restore transactional registry snapshots',
      options: {
        'list': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'List available snapshots', short: 'l', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":605,"end":610,"loc":{"start":{"line":19,"column":37,"index":605},"end":{"line":19,"column":42,"index":610}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the target without restoring it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":758,"end":763,"loc":{"start":{"line":24,"column":42,"index":758},"end":{"line":24,"column":47,"index":763}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/rollback'
    },
  'run': {
      name: 'run',
      description: 'Run a tool inside its selected identity',
      alias: 'x',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'allow-unverified': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Permit a configured VPN without verified leak prevention', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1058,"end":1063,"loc":{"start":{"line":35,"column":51,"index":1058},"end":{"line":35,"column":56,"index":1063}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/run'
    },
  'secret': {
      name: 'secret',
      description: 'Manage process-scoped secret references and backends',
      commands: [
        {
          name: 'set',
          description: 'Securely write a configured secret reference',
          options: {
            'stdin': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Read the value from standard input', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1442,"end":1447,"loc":{"start":{"line":54,"column":42,"index":1442},"end":{"line":54,"column":47,"index":1447}},"value":false}}]}, validator: '(val) => true' },
            'path': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Directory used to resolve a {{root}} template', short: 'C', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the target without reading a value', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1755,"end":1760,"loc":{"start":{"line":62,"column":46,"index":1755},"end":{"line":62,"column":51,"index":1760}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/secret'
        },
        {
          name: 'list',
          description: 'List credential references without reading their values',
          path: './src/commands/secret'
        },
        {
          name: 'backend',
          description: 'Show or select a local or password-manager secret backend',
          options: {
            'directory': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the file or age storage directory', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'recipient': { type: 'z.string.optional', required: false, hasDefault: false, description: 'age recipient used for encryption', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'identity-file': { type: 'z.string.optional', required: false, hasDefault: false, description: 'age identity file used for decryption', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'service': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Desktop keychain service name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'prefix': { type: 'z.string.optional', required: false, hasDefault: false, description: 'pass store prefix', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'app-data-directory': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Bitwarden CLI account data directory', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Validate and show the backend without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8217,"end":8222,"loc":{"start":{"line":236,"column":46,"index":8217},"end":{"line":236,"column":51,"index":8222}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/secret'
        }
      ],
      path: './src/commands/secret'
    },
  'setup': {
      name: 'setup',
      description: 'Configure the current project with an interactive wizard',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Project directory', short: 'C', fileType: 'directory', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Local identity to activate', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'tools': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Comma-separated tools for non-interactive setup', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'project': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Write a complete .ideality/project.jsonc handover bundle', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5068,"end":5073,"loc":{"start":{"line":160,"column":40,"index":5068},"end":{"line":160,"column":45,"index":5073}},"value":false}}]}, validator: '(val) => true' },
        'local-only': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Keep configuration only under the user ideality home', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5238,"end":5243,"loc":{"start":{"line":164,"column":45,"index":5238},"end":{"line":164,"column":50,"index":5243}},"value":false}}]}, validator: '(val) => true' },
        'advanced': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show SSH, handover, and integration controls', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5400,"end":5405,"loc":{"start":{"line":168,"column":41,"index":5400},"end":{"line":168,"column":46,"index":5405}},"value":false}}]}, validator: '(val) => true' },
        'requirements-only': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Share tool requirements without full identity profiles', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5565,"end":5570,"loc":{"start":{"line":172,"column":52,"index":5565},"end":{"line":172,"column":57,"index":5570}},"value":false}}]}, validator: '(val) => true' },
        'vm': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Run selected tools in this VM profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Require this host-enforced network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt; require identity and tool flags as needed', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5964,"end":5969,"loc":{"start":{"line":182,"column":50,"index":5964},"end":{"line":182,"column":55,"index":5969}},"value":false}}]}, validator: '(val) => true' },
        'yes': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Apply without the final confirmation', short: 'y', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6124,"end":6129,"loc":{"start":{"line":186,"column":36,"index":6124},"end":{"line":186,"column":41,"index":6129}},"value":false}}]}, validator: '(val) => true' },
        'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the complete change without writing files', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6289,"end":6294,"loc":{"start":{"line":191,"column":42,"index":6289},"end":{"line":191,"column":47,"index":6294}},"value":false}}]}, validator: '(val) => true' },
        'allow-policy-violations': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Bypass .ideality/policy.jsonc violations for this setup invocation', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":6462,"end":6467,"loc":{"start":{"line":195,"column":58,"index":6462},"end":{"line":195,"column":63,"index":6467}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/setup'
    },
  'status': {
      name: 'status',
      description: 'Show the identity active for a directory',
      alias: ["whoami","current"],
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
        'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Emit JSON', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":841,"end":846,"loc":{"start":{"line":23,"column":37,"index":841},"end":{"line":23,"column":42,"index":846}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/status'
    },
  'tool': {
      name: 'tool',
      description: 'Manage built-in and custom tool adapters',
      commands: [
        {
          name: 'list',
          description: 'List tool definitions',
          path: './src/commands/tool'
        },
        {
          name: 'packs',
          description: 'List built-in tool packs',
          path: './src/commands/tool'
        },
        {
          name: 'add',
          description: 'Register a custom executable',
          options: {
            'executable': { type: 'z.string', required: true, hasDefault: false, description: 'Executable name or path', short: 'x', fileType: 'path', schema: {"type":"zod","method":"string","args":[]}, validator: '(val) => true' },
            'isolation': { type: 'z.enum.default', required: true, hasDefault: true, default: "process", description: 'Environment scope', enumValues: ["shell","process"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"process"}]}, validator: '(val) => true' },
            'description': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Human-readable description', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":4530,"end":4535,"loc":{"start":{"line":123,"column":46,"index":4530},"end":{"line":123,"column":51,"index":4535}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'remove',
          description: 'Remove a tool definition and its identity profiles',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5660,"end":5665,"loc":{"start":{"line":155,"column":42,"index":5660},"end":{"line":155,"column":47,"index":5665}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5824,"end":5829,"loc":{"start":{"line":160,"column":46,"index":5824},"end":{"line":160,"column":51,"index":5829}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'env',
          description: 'Set a variable: secret:key, file:path, env:NAME, value:text, or unset',
          options: {
            'optional': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow a missing file or source variable', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7050,"end":7055,"loc":{"start":{"line":195,"column":45,"index":7050},"end":{"line":195,"column":50,"index":7055}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7216,"end":7221,"loc":{"start":{"line":199,"column":46,"index":7216},"end":{"line":199,"column":51,"index":7221}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        },
        {
          name: 'args',
          description: 'Replace identity-specific tool arguments',
          options: {
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the change without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":8656,"end":8661,"loc":{"start":{"line":233,"column":46,"index":8656},"end":{"line":233,"column":51,"index":8661}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/tool'
        }
      ],
      path: './src/commands/tool'
    },
  'tui': {
      name: 'tui',
      description: 'Open the interactive identity, plugin, and secret dashboard',
      options: {
        'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for initial identity selection', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' }
      },
      path: './src/commands/tui'
    },
  'vm': {
      name: 'vm',
      description: 'Manage isolated execution machines',
      commands: [
        {
          name: 'list',
          description: 'List VM profiles and backend availability',
          path: './src/commands/vm'
        },
        {
          name: 'show',
          description: 'Show one VM profile',
          path: './src/commands/vm'
        },
        {
          name: 'add',
          description: 'Create a VM profile with an interactive wizard or flags',
          options: {
            'id': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the automatically derived profile ID', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'label': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Display label', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'driver': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'VM backend', enumValues: ["lima","apple-vz","cloud-hypervisor","firecracker","custom"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'cpus': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 4, description: 'Virtual CPUs', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":4713,"end":4714,"loc":{"start":{"line":150,"column":60,"index":4713},"end":{"line":150,"column":61,"index":4714}},"extra":{"rawValue":4,"raw":"4"},"value":4}}]}, validator: '(val) => true' },
            'memory': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 4096, description: 'Memory in MiB', min: 256, minLength: 256, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":4834,"end":4838,"loc":{"start":{"line":153,"column":64,"index":4834},"end":{"line":153,"column":68,"index":4838}},"extra":{"rawValue":4096,"raw":"4096"},"value":4096}}]}, validator: '(val) => true' },
            'disk': { type: 'z.coerce.number.int.min.default', required: true, hasDefault: true, default: 40, description: 'Disk in GiB', min: 1, minLength: 1, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":4955,"end":4957,"loc":{"start":{"line":156,"column":60,"index":4955},"end":{"line":156,"column":62,"index":4957}},"extra":{"rawValue":40,"raw":"40"},"value":40}}]}, validator: '(val) => true' },
            'image': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Guest image URL or backend image reference', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'provision': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Lima system provisioning scripts as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'instance': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Backend instance name', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'vm-type': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Lima virtualization driver', enumValues: ["auto","vz","qemu"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'mount-type': { type: 'z.enum.optional', required: false, hasDefault: false, description: 'Lima filesystem transport', enumValues: ["auto","virtiofs","9p","reverse-sshfs"], schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'rosetta': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable Rosetta in an Apple VZ guest', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5758,"end":5763,"loc":{"start":{"line":176,"column":44,"index":5758},"end":{"line":176,"column":49,"index":5763}},"value":false}}]}, validator: '(val) => true' },
            'video': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Enable backend video output', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":5916,"end":5921,"loc":{"start":{"line":180,"column":42,"index":5916},"end":{"line":180,"column":47,"index":5921}},"value":false}}]}, validator: '(val) => true' },
            'guest-home': { type: 'z.string.default', required: true, hasDefault: true, default: "/home/ideality", description: 'Guest home used for path templates', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"/home/ideality"}]}, validator: '(val) => true' },
            'mount': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Host workspace mount source', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'workspace-target': { type: 'z.string.default', required: true, hasDefault: true, default: "/workspace", description: 'Guest workspace path', fileType: 'path', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"/workspace"}]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Host-enforced network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'helper': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Backend helper executable', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'start': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom start command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'stop': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom stop command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'status': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom status command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'exec': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Custom exec command as a JSON string array', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'non-interactive': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Never prompt', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7206,"end":7211,"loc":{"start":{"line":211,"column":54,"index":7206},"end":{"line":211,"column":59,"index":7211}},"value":false}}]}, validator: '(val) => true' },
            'dry-run': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Show the profile without saving it', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":7345,"end":7350,"loc":{"start":{"line":215,"column":46,"index":7345},"end":{"line":215,"column":51,"index":7350}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'bind',
          description: 'Route an identity or one tool through a VM and optional VPN',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override the VM network profile', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'unbind',
          description: 'Return an identity or one tool to host execution',
          options: {
            'tool': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Apply only to this tool', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
            'network': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Keep a host network requirement', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'start',
          description: 'Start a VM after enforcing its network',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'stop',
          description: 'Stop a VM',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'status',
          description: 'Read VM backend status',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'exec',
          description: 'Execute a command in a VM',
          options: {
            'path': { type: 'z.string.default', required: true, hasDefault: true, default: undefined, description: 'Path used for identity resolution', short: 'C', schema: {"type":"zod","method":"default","args":[{"type":"zod","method":"cwd","args":[]}]}, validator: '(val) => true' },
            'identity': { type: 'z.string.optional', required: false, hasDefault: false, description: 'Override folder-based selection', short: 'i', fileType: 'directory', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        },
        {
          name: 'remove',
          description: 'Remove an unused VM profile without deleting backend disks',
          options: {
            'force': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Confirm removal', short: 'f', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":22687,"end":22692,"loc":{"start":{"line":635,"column":42,"index":22687},"end":{"line":635,"column":47,"index":22692}},"value":false}}]}, validator: '(val) => true' }
          },
          path: './src/commands/vm'
        }
      ],
      path: './src/commands/vm'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
