#!/usr/bin/env bun
/**
 * Render the Homebrew formula for ideality from release checksums.
 *
 * Usage:
 *   bun scripts/homebrew-formula.ts \
 *     --version 0.1.0 \
 *     --repository 0xJord4n/ideality \
 *     --checksums dist/release/SHA256SUMS.txt \
 *     --out dist/release/ideality.rb
 */
import { readFile, writeFile } from "node:fs/promises";

const TARGETS = [
  "darwin-arm64",
  "darwin-x64",
  "linux-arm64",
  "linux-x64",
] as const;

type Target = (typeof TARGETS)[number];

interface FormulaInputs {
  version: string;
  repository: string;
  checksumsPath: string;
  outPath: string | undefined;
}

function parseArguments(argv: string[]): FormulaInputs {
  const values = new Map<string, string>();
  for (let index = 0; index < argv.length; index += 2) {
    const flag = argv[index];
    const value = argv[index + 1];
    if (!flag?.startsWith("--") || value === undefined) {
      throw new Error(`Unexpected argument '${flag ?? ""}'`);
    }
    values.set(flag.slice(2), value);
  }
  const version = values.get("version")?.replace(/^v/, "");
  const repository = values.get("repository");
  const checksumsPath = values.get("checksums");
  if (!version || !repository || !checksumsPath) {
    throw new Error(
      "Required: --version <x.y.z> --repository <owner/repo> --checksums <SHA256SUMS.txt>",
    );
  }
  return { version, repository, checksumsPath, outPath: values.get("out") };
}

function parseChecksums(content: string): Map<Target, string> {
  const sums = new Map<Target, string>();
  for (const line of content.split("\n")) {
    const match = line.match(/^([0-9a-f]{64})\s+\*?ideality-(\S+)\.tar\.gz$/);
    if (!match) continue;
    const target = match[2] as Target;
    if ((TARGETS as readonly string[]).includes(target)) {
      sums.set(target, match[1]!);
    }
  }
  return sums;
}

function renderFormula(
  version: string,
  repository: string,
  sums: Map<Target, string>,
): string {
  const base = `https://github.com/${repository}/releases/download/v${version}`;
  const block = (target: Target): string =>
    [
      `      url "${base}/ideality-${target}.tar.gz"`,
      `      sha256 "${sums.get(target)}"`,
    ].join("\n");
  return `# typed: false
# frozen_string_literal: true

# Generated by scripts/homebrew-formula.ts. Do not edit by hand.
class Ideality < Formula
  desc "Folder-based identity orchestration for developer tools"
  homepage "https://github.com/${repository}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
${block("darwin-arm64")}
    else
${block("darwin-x64")}
    end
  end

  on_linux do
    if Hardware::CPU.arm?
${block("linux-arm64")}
    else
${block("linux-x64")}
    end
  end

  def install
    bin.install "ideality"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ideality --version")
  end
end
`;
}

const inputs = parseArguments(process.argv.slice(2));
const sums = parseChecksums(await readFile(inputs.checksumsPath, "utf8"));
const missing = TARGETS.filter((target) => !sums.has(target));
if (missing.length > 0) {
  throw new Error(`Missing checksums for: ${missing.join(", ")}`);
}
const formula = renderFormula(inputs.version, inputs.repository, sums);
if (inputs.outPath) {
  await writeFile(inputs.outPath, formula);
  console.error(`Wrote ${inputs.outPath}`);
} else {
  process.stdout.write(formula);
}
